### ISSUE TITLE
UV breaks when trying to add cuts to the mesh

### ISSUE THREAD

**Issue by Genomo** [artempoletsky/blender_half_knife#1]
Hi! I really like your addon, but there is one problem that does not allow me to use it. If the model already has UV, when I try to cut the model with Half-Knife it breaks the UV (the knife, which is the default in Blender, doesn't break UVs).
![blender_DGQ3FDQL4e](https://github.com/user-attachments/assets/ab33986d-7911-4db2-932a-ca4086d63917)

**Comment by Dangry98** [comment]
> Hi! I really like your addon, but there is one problem that does not allow me to use it. If the model already has UV, when I try to cut the model with Half-Knife it breaks the UV (the knife, which is the default in Blender, doesn't break UVs). 

Hi @Genomo, Yeah, I also find it really annoying to be honest and I have been planning to fix it for a long time, I finally bite the bullet today and was able to solve the problem in the latest version of the add-on! 

Now it should work just like knife tool in Blender! The only issue is that it will still distort when cutting dircetly on a face, since its using poke + dissolve, wich I doubt is fixiable, but vert and edge should work perfectly now! 

Thank you for giving the motivation for me to finally fix it :)
